#
# Fusion Teleport
#   A decent teleportation plugin for servers that want to be able to teleport offline players.
#

# Amount of time players have to wait before running /rtp again
# Value must be an INTEGER representing SECONDS
rtpDelay: 30

# Worlds that you would like to be whitelisted (true) or blacklisted (false)
# World name should be the official name, not the friendly name (i.e "DIM1" not "The End")
rtpWorldWhitelist: false
rtpWorlds:
    # The End (FusionTP can't RTP in the End)
    - DIM1


# Don't touch!
# Seriously! I'm not a good enough programmer to know what will happen if you do!
version: 3