name: "FusionTP"
author: "Lord_Fusion"
version: "1.175"

main: "io.github.lordfusion.fusiontp.FusionTP"
softdepend: [Essentials, Multiverse-Core, WorldBorder]

commands:
  fusiontp:
    description: "Teleport one player to another player."
    usage: /<command> [player] [player]
    permission: fusion.tp.direct.to
    permission-message: "[Fusion] You don't have <permission>"
    aliases: [ftp]
  fusiontphere:
    description: "Teleport a player to you."
    usage: /<command> [player]
    permission: fusion.tp.direct.here
    permission-message: "[Fusion] You don't have <permission>"
    aliases: [ftphere, ftph]
  fusionspawntp:
    description: "Teleport a player to Spawn."
    usage: /<command> [player]
    permission: fusion.tp.direct.spawn
    permission-message: "[Fusion] You don't have <permission>"
    aliases: [fstp, fspawntp, spawntp, stp]
  fusionrandomtp:
    description: "Teleport to a random place in the world."
    usage: /<command>
    permission: fusion.tp.random
    permission-message: "[Fusion] You don't have <permission>"
    aliases: [frtp, rtp, randomtp]

  fusiontest:
    description: "DEVELOPERS ONLY: Test a method from the code."
    permission: fusion.developer
    permission-message: "[Fusion] You don't have <permission>"

permissions:
  fusion.*:
    description: Access to all commands across all Fusion plugins.
    children:
      fusion.developer: true
      fusion.tp.nodelay: true
      fusion.tp.*: true
    default: false

  fusion.tp.nodelay:
    description: Allows players to bypass the teleport cooldown
    children:
      fusion.tp.nodelay.cooldown: true
      fusion.tp.nodelay.warmup: true

  fusion.tp.*:
    description: Access to all teleporting commands
    children:
      fusion.tp.direct.to: true
      fusion.tp.direct.here: true
      fusion.tp.direct.spawn: true
      fusion.general: true

  fusion.general:
    description: Access to commands intended for the average player.
    children:
      fusion.tp.random: true
      fusion.about: true